// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"jumpToFailPage","status":false,"description":"玩家选择投降时自动跳转到失败页面 fail1.html","parameters":{}},
{"name":"QuickSaveLoad","status":false,"description":"快速存档/读档插件（支持指定存档槽）","parameters":{}},
{"name":"AutoSaveAndJump","status":true,"description":"自动存档并跳转到外部网页（例如fail1.html）","parameters":{"TargetURL":"../失败/fail1.html"}}
];
